codecov:
  notify:
    after_n_builds: 7
coverage:
  range: 50..95
  round: nearest
  precision: 1
  status:
    project:
      default:
        threshold: 15%
    patch:
      default:
        threshold: 20%
        target: 60%
  ignore:
    - "tools/*"
    - "geosnap/tests/*"
    - "geosnap/util/*"
    - "geosnap/visualize/*"
    - "geosnap/io/util.py"
    - "_version.py"
comment:
  layout: "reach, diff, files"
  behavior: once
  after_n_builds: 7
  require_changes: true
